package com.tiam.challenge.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Grants a challenge month to a phone number without a Mercado Pago
 * transaction behind it — for a buyer who paid through another channel
 * (transferencia, efectivo) and needs their access link generated by hand.
 * See {@link com.tiam.challenge.service.ChallengePurchaseService#grantManualPurchase}.
 *
 * <p>The upper bound on {@code challengeMonth} is deliberately NOT
 * duplicated here as a {@code @Max} — {@code ChallengePurchaseService}
 * already validates it against {@code MONTHS_ON_SALE}, and that's kept as
 * the single source of truth so a new month going on sale only requires
 * updating one constant.
 */
public record AdminGrantPurchaseRequest(
        @NotBlank String buyerName,
        @NotBlank String phone,
        @Email String email,
        @NotNull @Min(1) Integer challengeMonth) {
}
